# Single-service Render manifest for backend-only deployment
# Use this when you want to deploy only the backend as a Render web service.

services:
  - type: web
    name: campus-connect-backend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      npm ci
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        scope: env
      - key: JWT_SECRET
        scope: env
      - key: FRONTEND_URL
        scope: env
        # Optional: set to your frontend URL (e.g., https://your-frontend-host)
      - key: PORT
        scope: env
        value: "5000"
